name: Ci Pipeline for wisecow

on:
  workflow_dispatch:

permissions:
  contents: write
#Docker hub image repo
env:
  DOCKERHUB_REPO_1: harsh9308/wisecow


jobs:
  build-and-push-wisecow-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: installing depedency
        run: apt-get update && apt-get install -y --no-install-recommends \
            bash \
            cowsay \
            fortune-mod \
            fortunes-min \
            netcat-openbsd \
            && rm -rf /var/lib/apt/lists/*


      - name: Set image tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image for backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO_1 }}:latest
            ${{ env.DOCKERHUB_REPO_1 }}:${{ steps.tag.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  Update_manifest:
    needs: [build-and-push-wisecow-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Update Kubernetes backend deployment
        run: |
          sed -i "s|image: ${{ env.DOCKERHUB_REPO_1 }}:.*|image: ${{ env.DOCKERHUB_REPO_1 }}:${{ steps.tag.outputs.sha_short }}|" kubernetes/deployment.yml



      - name: Commit updated manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/deployment.yml
          git diff --staged --quiet || git commit -m "ci: update wisecow image to ${{ steps.tag.outputs.sha_short }} [skip ci]"
          git push
